<?php

use App\Models\Rule;
use App\Models\Admin;
use App\Models\Stock;
use App\Models\Currency;
use App\Models\GameSetup;
use App\Models\UserPolicy;
use App\Models\AdminPolicy;
use App\Models\PortalProvider;
use Illuminate\Database\Seeder;
use App\Models\ProviderGameSetup;
use Illuminate\Support\Facades\Crypt;
use Ramsey\Uuid\Uuid;

class basicSetup extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $currencies = [array('PID' => 1, 'name' => 'US Dollar', 'rate' => 100, 'symbol' => '$', 'abbreviation' => 'USD')];
        Currency::insert($currencies);

        $portalProviders = [
            array('PID' => 1, 'name' => 'TNKMaster', 'currencyID' => 1, 'creditBalance' => -1, 'mainBalance' => -1, 'UUID' => Uuid::uuid4()),
            array('PID' => 2, 'name' => 'PortalProvider_Test_1', 'currencyID' => 1, 'creditBalance' => 500000, 'mainBalance' => 500000, 'UUID' => Uuid::uuid4()),
            array('PID' => 3, 'name' => 'PortalProvider_Test_2', 'currencyID' => 1, 'creditBalance' => 10000, 'mainBalance' => 10000, 'UUID' => Uuid::uuid4()),
            array('PID' => 4, 'name' => 'Shareholder1', 'currencyID' => 1, 'creditBalance' => 1000000, 'mainBalance' => 1000000, 'UUID' => Uuid::uuid4())
        ];
        PortalProvider::insert($portalProviders);

        $adminPolicies = [
            array('PID' => 1, 'name' => 'TNKSuperUser', 'access' => 1, 'otpValidTimeInSeconds' => '60', 'source' => 1),
            array('PID' => 2, 'name' => 'TestProviderIOS', 'access' => 2, 'otpValidTimeInSeconds' => '60', 'source' => 3),
            array('PID' => 3, 'name' => 'Shareholder1_AdminPolicy', 'access' => 3, 'otpValidTimeInSeconds' => '60', 'source' => 2),
            array('PID' => 4, 'name' => 'Shareholder1_IOSPolicy', 'access' => 2, 'otpValidTimeInSeconds' => '60', 'source' => 3),
            array('PID' => 5, 'name' => 'TNK_WebApiPolicy', 'access' => 4, 'otpValidTimeInSeconds' => '300', 'source' => 2),
            array('PID' => 6, 'name' => 'TNK_AdminPolicy', 'access' => 3, 'otpValidTimeInSeconds' => '300', 'source' => 2),
        ];
        AdminPolicy::insert($adminPolicies);

        $admin = [
            array(
                'PID' => 1,
                'adminPolicyID' => 1,
                'portalProviderID' => 1,
                'emailID' => 'tnk@ECGaming.com',
                'firstName' => 'EC',
                'lastName' => 'Games',
                'username' => 'TNKSuper',
                'password' => Crypt::encrypt('Test123!')
            ),
            array(
                'PID' => 2,
                'adminPolicyID' => 2,
                'portalProviderID' => 2,
                'emailID' => 'TestPortalProviders@example.com',
                'firstName' => 'Provider 1',
                'lastName' => 'Admin',
                'username' => 'Test_PortalProvider',
                'password' => Crypt::encrypt('Test123!')
            ),
            array(
                'PID' => 3,
                'adminPolicyID' => 2,
                'portalProviderID' => 3,
                'emailID' => 'TestPortalProviders2@example.com',
                'firstName' => 'Provider 2',
                'lastName' => 'Admin',
                'username' => 'Test_PortalProvider2',
                'password' => Crypt::encrypt('Test123!')
            ),
            array(
                'PID' => 4,
                'adminPolicyID' => 3,
                'portalProviderID' => 4,
                'emailID' => 'tnk.laos.cn@gmail.com',
                'firstName' => '',
                'lastName' => '',
                'username' => 'ShareHolder1_Admin',
                'password' => Crypt::encrypt('H8NhUY4M')
            ),
            array(
                'PID' => 5,
                'adminPolicyID' => 4,
                'portalProviderID' => 4,
                'emailID' => 'subhamtnk11@gmail.com',
                'firstName' => '',
                'lastName' => '',
                'username' => 'SHolder1_IOS',
                'password' => Crypt::encrypt('D6yMYDTJ9mUz')
            ),
            array(
                'PID' => 6,
                'adminPolicyID' => 5,
                'portalProviderID' => 1,
                'emailID' => 'tnkWebApi@gmail.com',
                'firstName' => '',
                'lastName' => '',
                'username' => 'tnkWebApi',
                'password' => Crypt::encrypt('Test123!')
            ),
            array(
                'PID' => 7,
                'adminPolicyID' => 6,
                'portalProviderID' => 1,
                'emailID' => 'SandeshTnk11@gmail.com',
                'firstName' => '',
                'lastName' => '',
                'username' => 'TnkAdmin',
                'password' => Crypt::encrypt('Test123!')
            ),
        ];
        Admin::insert($admin);

        $userPolicy = [
            array('PID' => 1, 'name' => 'standardIOS'),
        ];
        UserPolicy::insert($userPolicy);

        $rule = [
            array('PID' => 1, 'name' => 'FD_BIG', 'isMatched' => '5,6,7,8,9'),
            array('PID' => 2, 'name' => 'FD_SMALL', 'isMatched' => '0,1,2,3,4'),
            array('PID' => 3, 'name' => 'FD_ODD', 'isMatched' => '1,3,5,7,9'),
            array('PID' => 4, 'name' => 'FD_EVEN', 'isMatched' => '0,2,4,6,8'),
            array('PID' => 5, 'name' => 'FD_HIGH', 'isMatched' => '0,1,2,3'),
            array('PID' => 6, 'name' => 'FD_MIDDLE', 'isMatched' => '4,5,6'),
            array('PID' => 7, 'name' => 'FD_LOW', 'isMatched' => '7,8,9'),
            array('PID' => 8, 'name' => 'FD_0', 'isMatched' => '0'),
            array('PID' => 9, 'name' => 'FD_1', 'isMatched' => '1'),
            array('PID' => 10, 'name' => 'FD_2', 'isMatched' => '2'),
            array('PID' => 11, 'name' => 'FD_3', 'isMatched' => '3'),
            array('PID' => 12, 'name' => 'FD_4', 'isMatched' => '4'),
            array('PID' => 13, 'name' => 'FD_5', 'isMatched' => '5'),
            array('PID' => 14, 'name' => 'FD_6', 'isMatched' => '6'),
            array('PID' => 15, 'name' => 'FD_7', 'isMatched' => '7'),
            array('PID' => 16, 'name' => 'FD_8', 'isMatched' => '8'),
            array('PID' => 17, 'name' => 'FD_9', 'isMatched' => '9'),

            array('PID' => 18, 'name' => 'LD_BIG', 'isMatched' => '5,6,7,8,9'),
            array('PID' => 19, 'name' => 'LD_SMALL', 'isMatched' => '0,1,2,3,4'),
            array('PID' => 20, 'name' => 'LD_ODD', 'isMatched' => '1,3,5,7,9'),
            array('PID' => 21, 'name' => 'LD_EVEN', 'isMatched' => '0,2,4,6,8'),
            array('PID' => 22, 'name' => 'LD_HIGH', 'isMatched' => '0,1,2,3'),
            array('PID' => 23, 'name' => 'LD_MIDDLE', 'isMatched' => '4,5,6'),
            array('PID' => 24, 'name' => 'LD_LOW', 'isMatched' => '7,8,9'),
            array('PID' => 25, 'name' => 'LD_0', 'isMatched' => '0'),
            array('PID' => 26, 'name' => 'LD_1', 'isMatched' => '1'),
            array('PID' => 27, 'name' => 'LD_2', 'isMatched' => '2'),
            array('PID' => 28, 'name' => 'LD_3', 'isMatched' => '3'),
            array('PID' => 29, 'name' => 'LD_4', 'isMatched' => '4'),
            array('PID' => 30, 'name' => 'LD_5', 'isMatched' => '5'),
            array('PID' => 31, 'name' => 'LD_6', 'isMatched' => '6'),
            array('PID' => 32, 'name' => 'LD_7', 'isMatched' => '7'),
            array('PID' => 33, 'name' => 'LD_8', 'isMatched' => '8'),
            array('PID' => 34, 'name' => 'LD_9', 'isMatched' => '9'),
            array('PID' => 35, 'name' => 'TD_BIG', 'isMatched' => '51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99'),
            array('PID' => 36, 'name' => 'TD_SMALL', 'isMatched' => '01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50'),
            array('PID' => 37, 'name' => 'TD_ODD', 'isMatched' => '03,05,07,09,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65,67,69,71,73,75,77,79,81,83,85,87,89,91,93,95,97,99'),
            array('PID' => 38, 'name' => 'TD_EVEN', 'isMatched' => '00,02,04,06,08,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98'),
            array('PID' => 39, 'name' => 'TD_HIGH', 'isMatched' => '00,01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33'),
            array('PID' => 40, 'name' => 'TD_MIDDLE', 'isMatched' => '34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66'),
            array('PID' => 41, 'name' => 'TD_LOW', 'isMatched' => '67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99'),
            array('PID' => 42, 'name' => 'TD_0', 'isMatched' => '00'),
            array('PID' => 43, 'name' => 'TD_1', 'isMatched' => '01'),
            array('PID' => 44, 'name' => 'TD_2', 'isMatched' => '02'),
            array('PID' => 45, 'name' => 'TD_3', 'isMatched' => '03'),
            array('PID' => 46, 'name' => 'TD_4', 'isMatched' => '04'),
            array('PID' => 47, 'name' => 'TD_5', 'isMatched' => '05'),
            array('PID' => 48, 'name' => 'TD_6', 'isMatched' => '06'),
            array('PID' => 49, 'name' => 'TD_7', 'isMatched' => '07'),
            array('PID' => 50, 'name' => 'TD_8', 'isMatched' => '08'),
            array('PID' => 51, 'name' => 'TD_9', 'isMatched' => '09'),
            array('PID' => 52, 'name' => 'TD_10', 'isMatched' => '10'),
            array('PID' => 53, 'name' => 'TD_11', 'isMatched' => '11'),
            array('PID' => 54, 'name' => 'TD_12', 'isMatched' => '12'),
            array('PID' => 55, 'name' => 'TD_13', 'isMatched' => '13'),
            array('PID' => 56, 'name' => 'TD_14', 'isMatched' => '14'),
            array('PID' => 57, 'name' => 'TD_15', 'isMatched' => '15'),
            array('PID' => 58, 'name' => 'TD_16', 'isMatched' => '16'),
            array('PID' => 59, 'name' => 'TD_17', 'isMatched' => '17'),
            array('PID' => 60, 'name' => 'TD_18', 'isMatched' => '18'),
            array('PID' => 61, 'name' => 'TD_19', 'isMatched' => '19'),
            array('PID' => 62, 'name' => 'TD_20', 'isMatched' => '20'),
            array('PID' => 63, 'name' => 'TD_21', 'isMatched' => '21'),
            array('PID' => 64, 'name' => 'TD_22', 'isMatched' => '22'),
            array('PID' => 65, 'name' => 'TD_23', 'isMatched' => '23'),
            array('PID' => 66, 'name' => 'TD_24', 'isMatched' => '24'),
            array('PID' => 67, 'name' => 'TD_25', 'isMatched' => '25'),
            array('PID' => 68, 'name' => 'TD_26', 'isMatched' => '26'),
            array('PID' => 69, 'name' => 'TD_27', 'isMatched' => '27'),
            array('PID' => 70, 'name' => 'TD_28', 'isMatched' => '28'),
            array('PID' => 71, 'name' => 'TD_29', 'isMatched' => '29'),
            array('PID' => 72, 'name' => 'TD_30', 'isMatched' => '30'),
            array('PID' => 73, 'name' => 'TD_31', 'isMatched' => '31'),
            array('PID' => 74, 'name' => 'TD_32', 'isMatched' => '32'),
            array('PID' => 75, 'name' => 'TD_33', 'isMatched' => '33'),
            array('PID' => 76, 'name' => 'TD_34', 'isMatched' => '34'),
            array('PID' => 77, 'name' => 'TD_35', 'isMatched' => '35'),
            array('PID' => 78, 'name' => 'TD_36', 'isMatched' => '36'),
            array('PID' => 79, 'name' => 'TD_37', 'isMatched' => '37'),
            array('PID' => 80, 'name' => 'TD_38', 'isMatched' => '38'),
            array('PID' => 81, 'name' => 'TD_39', 'isMatched' => '39'),
            array('PID' => 82, 'name' => 'TD_40', 'isMatched' => '40'),
            array('PID' => 83, 'name' => 'TD_41', 'isMatched' => '41'),
            array('PID' => 84, 'name' => 'TD_42', 'isMatched' => '42'),
            array('PID' => 85, 'name' => 'TD_43', 'isMatched' => '43'),
            array('PID' => 86, 'name' => 'TD_44', 'isMatched' => '44'),
            array('PID' => 87, 'name' => 'TD_45', 'isMatched' => '45'),
            array('PID' => 88, 'name' => 'TD_46', 'isMatched' => '46'),
            array('PID' => 89, 'name' => 'TD_47', 'isMatched' => '47'),
            array('PID' => 90, 'name' => 'TD_48', 'isMatched' => '48'),
            array('PID' => 91, 'name' => 'TD_49', 'isMatched' => '49'),
            array('PID' => 92, 'name' => 'TD_50', 'isMatched' => '50'),
            array('PID' => 93, 'name' => 'TD_51', 'isMatched' => '51'),
            array('PID' => 94, 'name' => 'TD_52', 'isMatched' => '52'),
            array('PID' => 95, 'name' => 'TD_53', 'isMatched' => '53'),
            array('PID' => 96, 'name' => 'TD_54', 'isMatched' => '54'),
            array('PID' => 97, 'name' => 'TD_55', 'isMatched' => '55'),
            array('PID' => 98, 'name' => 'TD_56', 'isMatched' => '56'),
            array('PID' => 99, 'name' => 'TD_57', 'isMatched' => '57'),
            array('PID' => 100, 'name' => 'TD_58', 'isMatched' => '58'),
            array('PID' => 101, 'name' => 'TD_59', 'isMatched' => '59'),
            array('PID' => 102, 'name' => 'TD_60', 'isMatched' => '60'),
            array('PID' => 103, 'name' => 'TD_61', 'isMatched' => '61'),
            array('PID' => 104, 'name' => 'TD_62', 'isMatched' => '62'),
            array('PID' => 105, 'name' => 'TD_63', 'isMatched' => '63'),
            array('PID' => 106, 'name' => 'TD_64', 'isMatched' => '64'),
            array('PID' => 107, 'name' => 'TD_65', 'isMatched' => '65'),
            array('PID' => 108, 'name' => 'TD_66', 'isMatched' => '66'),
            array('PID' => 109, 'name' => 'TD_67', 'isMatched' => '67'),
            array('PID' => 110, 'name' => 'TD_68', 'isMatched' => '68'),
            array('PID' => 111, 'name' => 'TD_69', 'isMatched' => '69'),
            array('PID' => 112, 'name' => 'TD_70', 'isMatched' => '70'),
            array('PID' => 113, 'name' => 'TD_71', 'isMatched' => '71'),
            array('PID' => 114, 'name' => 'TD_72', 'isMatched' => '72'),
            array('PID' => 115, 'name' => 'TD_73', 'isMatched' => '73'),
            array('PID' => 116, 'name' => 'TD_74', 'isMatched' => '74'),
            array('PID' => 117, 'name' => 'TD_75', 'isMatched' => '75'),
            array('PID' => 118, 'name' => 'TD_76', 'isMatched' => '76'),
            array('PID' => 119, 'name' => 'TD_77', 'isMatched' => '77'),
            array('PID' => 120, 'name' => 'TD_78', 'isMatched' => '78'),
            array('PID' => 121, 'name' => 'TD_79', 'isMatched' => '79'),
            array('PID' => 122, 'name' => 'TD_80', 'isMatched' => '80'),
            array('PID' => 123, 'name' => 'TD_81', 'isMatched' => '81'),
            array('PID' => 124, 'name' => 'TD_82', 'isMatched' => '82'),
            array('PID' => 125, 'name' => 'TD_83', 'isMatched' => '83'),
            array('PID' => 126, 'name' => 'TD_84', 'isMatched' => '84'),
            array('PID' => 127, 'name' => 'TD_85', 'isMatched' => '85'),
            array('PID' => 128, 'name' => 'TD_86', 'isMatched' => '86'),
            array('PID' => 129, 'name' => 'TD_87', 'isMatched' => '87'),
            array('PID' => 130, 'name' => 'TD_88', 'isMatched' => '88'),
            array('PID' => 131, 'name' => 'TD_89', 'isMatched' => '89'),
            array('PID' => 132, 'name' => 'TD_90', 'isMatched' => '90'),
            array('PID' => 133, 'name' => 'TD_91', 'isMatched' => '91'),
            array('PID' => 134, 'name' => 'TD_92', 'isMatched' => '92'),
            array('PID' => 135, 'name' => 'TD_93', 'isMatched' => '93'),
            array('PID' => 136, 'name' => 'TD_94', 'isMatched' => '94'),
            array('PID' => 137, 'name' => 'TD_95', 'isMatched' => '95'),
            array('PID' => 138, 'name' => 'TD_96', 'isMatched' => '96'),
            array('PID' => 139, 'name' => 'TD_97', 'isMatched' => '97'),
            array('PID' => 140, 'name' => 'TD_98', 'isMatched' => '98'),
            array('PID' => 141, 'name' => 'TD_99', 'isMatched' => '99'),

            array('PID' => 142, 'name' => 'BD_BIG', 'isMatched' => '10,11,12,13,14,15,16,17,18'),
            array('PID' => 143, 'name' => 'BD_SMALL', 'isMatched' => '1,2,3,4,5,6,7,8,9'),
            array('PID' => 144, 'name' => 'BD_ODD', 'isMatched' => '1,3,5,7,9,11,13,15,17'),
            array('PID' => 145, 'name' => 'BD_EVEN', 'isMatched' => '0,2,4,6,8,10,12,14,16,18'),
            array('PID' => 146, 'name' => 'BD_HIGH', 'isMatched' => '0,1,2,3,4,5'),
            array('PID' => 147, 'name' => 'BD_MIDDLE', 'isMatched' => '6,7,8,9,10,11'),
            array('PID' => 148, 'name' => 'BD_LOW', 'isMatched' => '12,13,14,15,16,17,18'),
            array('PID' => 149, 'name' => 'BD_0', 'isMatched' => '00'),
            array('PID' => 150, 'name' => 'BD_1', 'isMatched' => '01'),
            array('PID' => 151, 'name' => 'BD_2', 'isMatched' => '02'),
            array('PID' => 152, 'name' => 'BD_3', 'isMatched' => '03'),
            array('PID' => 153, 'name' => 'BD_4', 'isMatched' => '04'),
            array('PID' => 154, 'name' => 'BD_5', 'isMatched' => '05'),
            array('PID' => 155, 'name' => 'BD_6', 'isMatched' => '06'),
            array('PID' => 156, 'name' => 'BD_7', 'isMatched' => '07'),
            array('PID' => 157, 'name' => 'BD_8', 'isMatched' => '08'),
            array('PID' => 158, 'name' => 'BD_9', 'isMatched' => '09'),
            array('PID' => 159, 'name' => 'BD_10', 'isMatched' => '10'),
            array('PID' => 160, 'name' => 'BD_11', 'isMatched' => '11'),
            array('PID' => 161, 'name' => 'BD_12', 'isMatched' => '12'),
            array('PID' => 162, 'name' => 'BD_13', 'isMatched' => '13'),
            array('PID' => 163, 'name' => 'BD_14', 'isMatched' => '14'),
            array('PID' => 164, 'name' => 'BD_15', 'isMatched' => '15'),
            array('PID' => 165, 'name' => 'BD_16', 'isMatched' => '16'),
            array('PID' => 166, 'name' => 'BD_17', 'isMatched' => '17'),
            array('PID' => 167, 'name' => 'BD_18', 'isMatched' => '18'),

            array('PID' => 168, 'name' => 'TD_TIE', 'isMatched' => '00'),
            array('PID' => 169, 'name' => 'BD_TIE', 'isMatched' => '00'),

        ];
        Rule::insert($rule);

        $gameSetup = [
            array('PID' => 1, 'rulesID' => '1,2', 'gameName' => 'FD_BigSmall', 'initialOdd' => 2.0, 'commission' => 5, 'gameLoop' => 5),
            array('PID' => 2, 'rulesID' => '3,4', 'gameName' => 'FD_OddEven', 'initialOdd' => 2.0, 'commission' => 5, 'gameLoop' => 5),
            array('PID' => 3, 'rulesID' => '5,6,7', 'gameName' => 'FD_HighMiddleLow', 'initialOdd' => 3.0, 'commission' => 5, 'gameLoop' => 5),
            array('PID' => 4, 'rulesID' => '8,9,10,11,12,13,14,15,16,17', 'gameName' => 'FD_Number', 'initialOdd' => 10.0, 'commission' => 5, 'gameLoop' => 5),

            array('PID' => 5, 'rulesID' => '18,19', 'gameName' => 'LD_BigSmall', 'initialOdd' => 2.0, 'commission' => 5, 'gameLoop' => 5),
            array('PID' => 6, 'rulesID' => '20,21', 'gameName' => 'LD_OddEven', 'initialOdd' => 2.0, 'commission' => 5, 'gameLoop' => 5),
            array('PID' => 7, 'rulesID' => '22,23,24', 'gameName' => 'LD_HighMiddleLow', 'initialOdd' => 3.0, 'commission' => 5, 'gameLoop' => 5),
            array('PID' => 8, 'rulesID' => '25,26,27,28,29,30,31,32,33,34', 'gameName' => 'LD_Number', 'initialOdd' => 10.0, 'commission' => 5, 'gameLoop' => 5),

            array('PID' => 9, 'rulesID' => '35,36,168', 'gameName' => 'TD_BigSmallTie', 'initialOdd' => 2.0, 'commission' => 5, 'gameLoop' => 5),
            array('PID' => 10, 'rulesID' => '37,38', 'gameName' => 'TD_OddEven', 'initialOdd' => 2.0, 'commission' => 5, 'gameLoop' => 5),
            array('PID' => 11, 'rulesID' => '39,40,41', 'gameName' => 'TD_HighMiddleLow', 'initialOdd' => 3.0, 'commission' => 5, 'gameLoop' => 5),
            array('PID' => 12, 'rulesID' => '42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141', 'gameName' => 'TD_Number', 'initialOdd' => 100.0, 'commission' => 5, 'gameLoop' => 5),

            array('PID' => 13, 'rulesID' => '142,143,169', 'gameName' => 'BD_BigSmallTie', 'initialOdd' => 3.0, 'commission' => 5, 'gameLoop' => 5),
            array('PID' => 14, 'rulesID' => '144,145', 'gameName' => 'BD_OddEven', 'initialOdd' => 2.0, 'commission' => 5, 'gameLoop' => 5),
            array('PID' => 15, 'rulesID' => '146,147,148', 'gameName' => 'BD_HighMiddleLow', 'initialOdd' => 3.0, 'commission' => 5, 'gameLoop' => 5),
            array('PID' => 16, 'rulesID' => '149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167', 'gameName' => 'BD_Number', 'initialOdd' => 19.0, 'commission' => 5, 'gameLoop' => 5),

            array('PID' => 17, 'rulesID' => '1,2', 'gameName' => 'FD_BigSmall', 'initialOdd' => 2.0, 'commission' => 5, 'gameLoop' => 1),
            array('PID' => 18, 'rulesID' => '3,4', 'gameName' => 'FD_OddEven', 'initialOdd' => 2.0, 'commission' => 5, 'gameLoop' => 1),
            array('PID' => 19, 'rulesID' => '5,6,7', 'gameName' => 'FD_HighMiddleLow', 'initialOdd' => 3.0, 'commission' => 5, 'gameLoop' => 1),
            array('PID' => 20, 'rulesID' => '8,9,10,11,12,13,14,15,16,17', 'gameName' => 'FD_Number', 'initialOdd' => 10.0, 'commission' => 5, 'gameLoop' => 1),

            array('PID' => 21, 'rulesID' => '18,19', 'gameName' => 'LD_BigSmall', 'initialOdd' => 2.0, 'commission' => 5, 'gameLoop' => 1),
            array('PID' => 22, 'rulesID' => '20,21', 'gameName' => 'LD_OddEven', 'initialOdd' => 2.0, 'commission' => 5, 'gameLoop' => 1),
            array('PID' => 23, 'rulesID' => '22,23,24', 'gameName' => 'LD_HighMiddleLow', 'initialOdd' => 3.0, 'commission' => 5, 'gameLoop' => 1),
            array('PID' => 24, 'rulesID' => '25,26,27,28,29,30,31,32,33,34', 'gameName' => 'LD_Number', 'initialOdd' => 10.0, 'commission' => 5, 'gameLoop' => 1),

            array('PID' => 25, 'rulesID' => '35,36,168', 'gameName' => 'TD_BigSmallTie', 'initialOdd' => 3.0, 'commission' => 5, 'gameLoop' => 1),
            array('PID' => 26, 'rulesID' => '37,38', 'gameName' => 'TD_OddEven', 'initialOdd' => 2.0, 'commission' => 5, 'gameLoop' => 1),
            array('PID' => 27, 'rulesID' => '39,40,41', 'gameName' => 'TD_HighMiddleLow', 'initialOdd' => 3.0, 'commission' => 5, 'gameLoop' => 1),
            array('PID' => 28, 'rulesID' => '42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141', 'gameName' => 'TD_Number', 'initialOdd' => 100.0, 'commission' => 5, 'gameLoop' => 1),

            array('PID' => 29, 'rulesID' => '142,143,169', 'gameName' => 'BD_BigSmallTie', 'initialOdd' => 3.0, 'commission' => 5, 'gameLoop' => 1),
            array('PID' => 30, 'rulesID' => '144,145', 'gameName' => 'BD_OddEven', 'initialOdd' => 2.0, 'commission' => 5, 'gameLoop' => 1),
            array('PID' => 31, 'rulesID' => '146,147,148', 'gameName' => 'BD_HighMiddleLow', 'initialOdd' => 3.0, 'commission' => 5, 'gameLoop' => 1),
            array('PID' => 32, 'rulesID' => '149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167', 'gameName' => 'BD_Number', 'initialOdd' => 19.0, 'commission' => 5, 'gameLoop' => 1),

        ];
        GameSetup::insert($gameSetup);

        $stock = [
            array(
                'PID' => 1,
                'name' => 'sh000001',
                'ReferenceURL' => 'http://finance.sina.com.cn/realstock/company/sh000001/nc.shtml',
                'country' => 'china',
                "stockLoop" => 5,
                'betCloseSec' => 60,
                'closeDays' => '0,6',
                "method" => "GET",
                'url' => 'http://money.finance.sina.com.cn/quotes_service/api/json_v2.php/CN_MarketData.getKLineData?symbol=sh000001&scale=5&ma=no',
                'limitTag' => 'datalen',
                'openTimeRange' => '09:30-11:30,13:25-15:00',
                'timeZone' => 'Asia/Shanghai',
                'category' => 'china',
                'precision' => 3,
                'responseType' => 'string',
                'responseStockOpenTag' => 'open',
                'responseStockTimeTag' => 'day',
                'responseStockTimeZone' => 'Asia/Shanghai',
                'responseStockTimeFormat' => 'Y-m-d H:i:s',
                'responseStockDataTag' => null,
                'replaceJsonRules' => '[{"search": "{day:","replace": "{\"day\":"},{"search": ",open:","replace": ",\"open\":"},{"search": ",high:","replace": ",\"high\":"},{"search": ",low:","replace": ",\"low\":"},{"search": ",close:","replace": ",\"close\":"},{"search": ",volume:","replace": ",\"volume\":"}]',
                'liveStockUrl' => 'https://hq.sinajs.cn/?rn=1552280540946&list=sh000001',
                'liveStockResponseType' => 'stringSplit',
                'liveStockOpenTag' => null,
                'liveStockTimeTag' => null,
                'splitString' => ',',
                'openValueIndex' => 1,
                'dateValueIndex' => 30,
                'timeValueIndex' => 31,
                'liveStockDataTag' => null,
                'liveStockReplaceJsonRules' => null,
                'UUID' => Uuid::uuid4(),
            ),
            array(
                'PID' => 2,
                'name' => 'sh000300',
                'ReferenceURL' => 'http://finance.sina.com.cn/realstock/company/sh000300/nc.shtml',
                'country' => 'china',
                "stockLoop" => 5,
                'betCloseSec' => 60,
                'closeDays' => '0,6',
                "method" => "GET",
                'url' => 'https://quotes.sina.cn/cn/api/jsonp_v2.php/var%20_sh000001_5_1553569576264=/CN_MarketDataService.getKLineData?symbol=sh000300&scale=5&ma=no',
                'limitTag' => 'datalen',
                'openTimeRange' => '09:30-11:30,13:25-15:00',
                'timeZone' => 'Asia/Shanghai',
                'category' => 'china',
                'precision' => 3,
                'responseType' => 'string',
                'responseStockOpenTag' => 'open',
                'responseStockTimeTag' => 'day',
                'responseStockTimeZone' => 'Asia/Shanghai',
                'responseStockTimeFormat' => 'Y-m-d H:i:s',
                'responseStockDataTag' => null,
                'replaceJsonRules' => '[{"search": "/*<script>location.href=\'//sina.com\';</script>*/","replace": ""},{"search": "var _sh000001_5_1553569576264=(","replace": ""},{"search": "}]);","replace": "}]"}]',
                'liveStockUrl' => 'https://hq.sinajs.cn/etag.php?_=1553569520963&list=sh000300',
                'liveStockResponseType' => 'stringSplit',
                'liveStockOpenTag' => null,
                'liveStockTimeTag' => null,
                'splitString' => ',',
                'openValueIndex' => 1,
                'dateValueIndex' => 30,
                'timeValueIndex' => 31,
                'liveStockDataTag' => null,
                'liveStockReplaceJsonRules' => null,
                'UUID' => Uuid::uuid4(),
            ),
            array(
                'PID' => 3,
                'name' => 'sz399415',
                'ReferenceURL' => 'http://finance.sina.com.cn/realstock/company/sz399415/nc.shtml',
                'country' => 'china',
                "stockLoop" => 5,
                'betCloseSec' => 60,
                'closeDays' => '0,6',
                "method" => "GET",
                'url' => 'http://money.finance.sina.com.cn/quotes_service/api/json_v2.php/CN_MarketData.getKLineData?symbol=sz399415&scale=5&ma=no',
                'limitTag' => 'datalen',
                'openTimeRange' => '09:30-11:30,13:25-15:00',
                'timeZone' => 'Asia/Shanghai',
                'category' => 'china',
                'precision' => 3,
                'responseType' => 'string',
                'responseStockOpenTag' => 'open',
                'responseStockTimeTag' => 'day',
                'responseStockTimeZone' => 'Asia/Shanghai',
                'responseStockTimeFormat' => 'Y-m-d H:i:s',
                'responseStockDataTag' => null,
                'replaceJsonRules' => '[{"search": "{day:","replace": "{\"day\":"},{"search": ",open:","replace": ",\"open\":"},{"search": ",high:","replace": ",\"high\":"},{"search": ",low:","replace": ",\"low\":"},{"search": ",close:","replace": ",\"close\":"},{"search": ",volume:","replace": ",\"volume\":"}]',
                'liveStockUrl' => 'https://hq.sinajs.cn/etag.php?_=1553569520963&list=sz399415',
                'liveStockResponseType' => 'stringSplit',
                'liveStockOpenTag' => null,
                'liveStockTimeTag' => null,
                'splitString' => ',',
                'openValueIndex' => 1,
                'dateValueIndex' => 30,
                'timeValueIndex' => 31,
                'liveStockDataTag' => null,
                'liveStockReplaceJsonRules' => null,
                'UUID' => Uuid::uuid4(),
            ),
            array(
                'PID' => 4,
                'name' => 'sz399001',
                'ReferenceURL' => 'http://finance.sina.com.cn/realstock/company/sz399001/nc.shtml',
                'country' => 'china',
                "stockLoop" => 5,
                'betCloseSec' => 60,
                'closeDays' => '0,6',
                "method" => "GET",
                'url' => 'http://money.finance.sina.com.cn/quotes_service/api/json_v2.php/CN_MarketData.getKLineData?symbol=sz399001&scale=5&ma=no',
                'limitTag' => 'datalen',
                'openTimeRange' => '09:30-11:30,13:25-15:00',
                'timeZone' => 'Asia/Shanghai',
                'category' => 'china',
                'precision' => 3,
                'responseType' => 'string',
                'responseStockOpenTag' => 'open',
                'responseStockTimeTag' => 'day',
                'responseStockTimeZone' => 'Asia/Shanghai',
                'responseStockTimeFormat' => 'Y-m-d H:i:s',
                'responseStockDataTag' => null,
                'replaceJsonRules' => '[{"search": "{day:","replace": "{\"day\":"},{"search": ",open:","replace": ",\"open\":"},{"search": ",high:","replace": ",\"high\":"},{"search": ",low:","replace": ",\"low\":"},{"search": ",close:","replace": ",\"close\":"},{"search": ",volume:","replace": ",\"volume\":"}]',
                'liveStockUrl' => 'https://hq.sinajs.cn/etag.php?_=1553569520963&list=sz399001',
                'liveStockResponseType' => 'stringSplit',
                'liveStockOpenTag' => null,
                'liveStockTimeTag' => null,
                'splitString' => ',',
                'openValueIndex' => 1,
                'dateValueIndex' => 30,
                'timeValueIndex' => 31,
                'liveStockDataTag' => null,
                'liveStockReplaceJsonRules' => null,
                'UUID' => Uuid::uuid4(),
            ),
            array(
                'PID' => 5,
                'name' => 'usindex',
                'ReferenceURL' => 'https://finance.sina.com.cn/money/forex/hq/DINIW.shtml',
                'country' => 'china',
                "stockLoop" => 5,
                'betCloseSec' => 60,
                'closeDays' => '0',
                "method" => "GET",
                'url' => 'http://vip.stock.finance.sina.com.cn/forex/api/jsonp.php/var%20_DINIW_01=/NewForexService.getOldMinKline?symbol=DINIW&scale=5',
                'limitTag' => 'datalen',
                'openTimeRange' => NULL,
                'timeZone' => 'Asia/Shanghai',
                'category' => 'usa',
                'precision' => 4,
                'responseType' => 'string',
                'responseStockOpenTag' => 'o',
                'responseStockTimeTag' => 'd',
                'responseStockTimeZone' => 'Asia/Shanghai',
                'responseStockTimeFormat' => 'Y-m-d H:i:s',
                'responseStockDataTag' => null,
                'replaceJsonRules' => '[{"search": "}]);", "replace": "}]"}, {"search": "//<script>location.href=\'http://sina.com.cn\'; </script>", "replace": ""}, {"search": "/*<script>location.href=\'//sina.com\';</script>*/", "replace": ""}, {"search": "var _DINIW_01=(", "replace": ""}, {"search": "}])", "replace": "}]"}, {"search": "{d:", "replace": "{\"d\":"}, {"search": ",o:", "replace": ",\"o\":"}, {"search": ",h:", "replace": ",\"h\":"}, {"search": ",l:", "replace": ",\"l\":"}, {"search": ",c:", "replace": ",\"c\":"}, {"search": ",p:", "replace": ",\"p\":"}]',                'liveStockUrl' => 'http://hq.sinajs.cn/rn=1553570744061list=DINIW',
                'liveStockResponseType' => 'stringSplit',
                'liveStockOpenTag' => null,
                'liveStockTimeTag' => null,
                'splitString' => ',',
                'openValueIndex' => 1,
                'dateValueIndex' => 10,
                'timeValueIndex' => 0,
                'liveStockDataTag' => null,
                'liveStockReplaceJsonRules' => '[{"search": "var hq_str_DINIW=\"","replace": ""},{"search": "\"","replace": ""},{"search": ";","replace": ""},{"search": "\n","replace": ""}]',
                'UUID' => Uuid::uuid4(),
            ),
            array(
                'PID' => 6,
                'name' => 'btc5',
                'ReferenceURL' => 'https://www.hbg.com/zh-cn/exchange/?s=btc_usdt',
                'country' => 'china',
                "stockLoop" => 5,
                'betCloseSec' => 60,
                'closeDays' => '',
                "method" => "GET",
                'url' => 'https://api.huobi.pro/market/history/kline?period=5min&symbol=btcusdt',
                'limitTag' => 'size',
                'openTimeRange' => NULL,
                'timeZone' => 'Asia/Shanghai',
                'category' => 'crypto',
                'precision' => 2,
                'responseType' => 'JSON',
                'responseStockOpenTag' => 'open',
                'responseStockTimeTag' => 'id',
                'responseStockTimeZone' => 'utc',
                'responseStockTimeFormat' => 'U',
                'responseStockDataTag' => 'data',
                'replaceJsonRules' => null,
                'liveStockUrl' => 'https://api.huobi.pro/market/trade?symbol=btcusdt',
                'liveStockResponseType' => 'JSON',
                'liveStockOpenTag' => 'price',
                'liveStockTimeTag' => 'ts',
                'splitString' => null,
                'openValueIndex' => null,
                'dateValueIndex' => null,
                'timeValueIndex' => null,
                'liveStockDataTag' => 'tick/data',
                'liveStockReplaceJsonRules' => null,
                'UUID' => Uuid::uuid4(),
            ),
            array(
                'PID' => 7,
                'name' => 'btc1',
                'ReferenceURL' => 'https://www.hbg.com/zh-cn/exchange/?s=btc_usdt',
                'country' => 'china',
                "stockLoop" => 1,
                'betCloseSec' => 20,
                'closeDays' => '',
                "method" => "GET",
                'url' => 'https://api.huobi.pro/market/history/kline?period=1min&symbol=btcusdt',
                'limitTag' => 'size',
                'openTimeRange' => NULL,
                'timeZone' => 'Asia/Shanghai',
                'category' => 'crypto',
                'precision' => 2,
                'responseType' => 'JSON',
                'responseStockOpenTag' => 'open',
                'responseStockTimeTag' => 'id',
                'responseStockTimeZone' => 'utc',
                'responseStockTimeFormat' => 'U',
                'responseStockDataTag' => 'data',
                'replaceJsonRules' => null,
                'liveStockUrl' => 'https://api.huobi.pro/market/trade?symbol=btcusdt',
                'liveStockResponseType' => 'JSON',
                'liveStockOpenTag' => 'price',
                'liveStockTimeTag' => 'ts',
                'splitString' => null,
                'openValueIndex' => null,
                'dateValueIndex' => null,
                'timeValueIndex' => null,
                'liveStockDataTag' => 'tick/data',
                'liveStockReplaceJsonRules' => null,
                'UUID' => Uuid::uuid4(),
            ),
        ];
        Stock::insert($stock);

        $providerGameSetup = [
            array('PID' => 1, 'portalProviderID' => 2, 'stockID' => 1, "payoutType" => 1, 'FD_BigSmallGameID' => 1, 'FD_EvenOddGameID' => 2, 'FD_LowMiddleHighGameID' => 3, 'FD_NumberGameID' => 4, 'LD_BigSmallGameID' => 5, 'LD_EvenOddGameID' => 6, 'LD_LowMiddleHighGameID' => 7, 'LD_NumberGameID' => 8, 'TD_BigSmallTieGameID' => 9, 'TD_EvenOddGameID' => 10, 'TD_LowMiddleHighGameID' => 11, 'TD_NumberGameID' => 12, 'BD_BigSmallTieGameID' => 13, 'BD_EvenOddGameID' => 14, 'BD_LowMiddleHighGameID' => 15, 'BD_NumberGameID' => 16),
            array('PID' => 2, 'portalProviderID' => 2, 'stockID' => 2, "payoutType" => 1, 'FD_BigSmallGameID' => 1, 'FD_EvenOddGameID' => 2, 'FD_LowMiddleHighGameID' => 3, 'FD_NumberGameID' => 4, 'LD_BigSmallGameID' => 5, 'LD_EvenOddGameID' => 6, 'LD_LowMiddleHighGameID' => 7, 'LD_NumberGameID' => 8, 'TD_BigSmallTieGameID' => 9, 'TD_EvenOddGameID' => 10, 'TD_LowMiddleHighGameID' => 11, 'TD_NumberGameID' => 12, 'BD_BigSmallTieGameID' => 13, 'BD_EvenOddGameID' => 14, 'BD_LowMiddleHighGameID' => 15, 'BD_NumberGameID' => 16),
            array('PID' => 3, 'portalProviderID' => 2, 'stockID' => 3, "payoutType" => 1, 'FD_BigSmallGameID' => 1, 'FD_EvenOddGameID' => 2, 'FD_LowMiddleHighGameID' => 3, 'FD_NumberGameID' => 4, 'LD_BigSmallGameID' => 5, 'LD_EvenOddGameID' => 6, 'LD_LowMiddleHighGameID' => 7, 'LD_NumberGameID' => 8, 'TD_BigSmallTieGameID' => 9, 'TD_EvenOddGameID' => 10, 'TD_LowMiddleHighGameID' => 11, 'TD_NumberGameID' => 12, 'BD_BigSmallTieGameID' => 13, 'BD_EvenOddGameID' => 14, 'BD_LowMiddleHighGameID' => 15, 'BD_NumberGameID' => 16),
            array('PID' => 4, 'portalProviderID' => 2, 'stockID' => 4, "payoutType" => 1, 'FD_BigSmallGameID' => 1, 'FD_EvenOddGameID' => 2, 'FD_LowMiddleHighGameID' => 3, 'FD_NumberGameID' => 4, 'LD_BigSmallGameID' => 5, 'LD_EvenOddGameID' => 6, 'LD_LowMiddleHighGameID' => 7, 'LD_NumberGameID' => 8, 'TD_BigSmallTieGameID' => 9, 'TD_EvenOddGameID' => 10, 'TD_LowMiddleHighGameID' => 11, 'TD_NumberGameID' => 12, 'BD_BigSmallTieGameID' => 13, 'BD_EvenOddGameID' => 14, 'BD_LowMiddleHighGameID' => 15, 'BD_NumberGameID' => 16),
            array('PID' => 5, 'portalProviderID' => 2, 'stockID' => 5, "payoutType" => 1, 'FD_BigSmallGameID' => 1, 'FD_EvenOddGameID' => 2, 'FD_LowMiddleHighGameID' => 3, 'FD_NumberGameID' => 4, 'LD_BigSmallGameID' => 5, 'LD_EvenOddGameID' => 6, 'LD_LowMiddleHighGameID' => 7, 'LD_NumberGameID' => 8, 'TD_BigSmallTieGameID' => 9, 'TD_EvenOddGameID' => 10, 'TD_LowMiddleHighGameID' => 11, 'TD_NumberGameID' => 12, 'BD_BigSmallTieGameID' => 13, 'BD_EvenOddGameID' => 14, 'BD_LowMiddleHighGameID' => 15, 'BD_NumberGameID' => 16),
            array('PID' => 6, 'portalProviderID' => 2, 'stockID' => 6, "payoutType" => 1, 'FD_BigSmallGameID' => 1, 'FD_EvenOddGameID' => 2, 'FD_LowMiddleHighGameID' => 3, 'FD_NumberGameID' => 4, 'LD_BigSmallGameID' => 5, 'LD_EvenOddGameID' => 6, 'LD_LowMiddleHighGameID' => 7, 'LD_NumberGameID' => 8, 'TD_BigSmallTieGameID' => 9, 'TD_EvenOddGameID' => 10, 'TD_LowMiddleHighGameID' => 11, 'TD_NumberGameID' => 12, 'BD_BigSmallTieGameID' => 13, 'BD_EvenOddGameID' => 14, 'BD_LowMiddleHighGameID' => 15, 'BD_NumberGameID' => 16),
            array('PID' => 7, 'portalProviderID' => 2, 'stockID' => 7, "payoutType" => 1, 'FD_BigSmallGameID' => 17, 'FD_EvenOddGameID' => 18, 'FD_LowMiddleHighGameID' => 19, 'FD_NumberGameID' => 20, 'LD_BigSmallGameID' => 21, 'LD_EvenOddGameID' => 22, 'LD_LowMiddleHighGameID' => 23, 'LD_NumberGameID' => 24, 'TD_BigSmallTieGameID' => 25, 'TD_EvenOddGameID' => 26, 'TD_LowMiddleHighGameID' => 27, 'TD_NumberGameID' => 28, 'BD_BigSmallTieGameID' => 29, 'BD_EvenOddGameID' => 30, 'BD_LowMiddleHighGameID' => 31, 'BD_NumberGameID' => 32),

            array('PID' => 8, 'portalProviderID' => 3, 'stockID' => 1, "payoutType" => 1, 'FD_BigSmallGameID' => 1, 'FD_EvenOddGameID' => 2, 'FD_LowMiddleHighGameID' => 3, 'FD_NumberGameID' => 4, 'LD_BigSmallGameID' => 5, 'LD_EvenOddGameID' => 6, 'LD_LowMiddleHighGameID' => 7, 'LD_NumberGameID' => 8, 'TD_BigSmallTieGameID' => 9, 'TD_EvenOddGameID' => 10, 'TD_LowMiddleHighGameID' => 11, 'TD_NumberGameID' => 12, 'BD_BigSmallTieGameID' => 13, 'BD_EvenOddGameID' => 14, 'BD_LowMiddleHighGameID' => 15, 'BD_NumberGameID' => 16),
            array('PID' => 9, 'portalProviderID' => 3, 'stockID' => 2, "payoutType" => 1, 'FD_BigSmallGameID' => 1, 'FD_EvenOddGameID' => 2, 'FD_LowMiddleHighGameID' => 3, 'FD_NumberGameID' => 4, 'LD_BigSmallGameID' => 5, 'LD_EvenOddGameID' => 6, 'LD_LowMiddleHighGameID' => 7, 'LD_NumberGameID' => 8, 'TD_BigSmallTieGameID' => 9, 'TD_EvenOddGameID' => 10, 'TD_LowMiddleHighGameID' => 11, 'TD_NumberGameID' => 12, 'BD_BigSmallTieGameID' => 13, 'BD_EvenOddGameID' => 14, 'BD_LowMiddleHighGameID' => 15, 'BD_NumberGameID' => 16),
            array('PID' => 10, 'portalProviderID' => 3, 'stockID' => 3, "payoutType" => 1, 'FD_BigSmallGameID' => 1, 'FD_EvenOddGameID' => 2, 'FD_LowMiddleHighGameID' => 3, 'FD_NumberGameID' => 4, 'LD_BigSmallGameID' => 5, 'LD_EvenOddGameID' => 6, 'LD_LowMiddleHighGameID' => 7, 'LD_NumberGameID' => 8, 'TD_BigSmallTieGameID' => 9, 'TD_EvenOddGameID' => 10, 'TD_LowMiddleHighGameID' => 11, 'TD_NumberGameID' => 12, 'BD_BigSmallTieGameID' => 13, 'BD_EvenOddGameID' => 14, 'BD_LowMiddleHighGameID' => 15, 'BD_NumberGameID' => 16),
            array('PID' => 11, 'portalProviderID' => 3, 'stockID' => 4, "payoutType" => 1, 'FD_BigSmallGameID' => 1, 'FD_EvenOddGameID' => 2, 'FD_LowMiddleHighGameID' => 3, 'FD_NumberGameID' => 4, 'LD_BigSmallGameID' => 5, 'LD_EvenOddGameID' => 6, 'LD_LowMiddleHighGameID' => 7, 'LD_NumberGameID' => 8, 'TD_BigSmallTieGameID' => 9, 'TD_EvenOddGameID' => 10, 'TD_LowMiddleHighGameID' => 11, 'TD_NumberGameID' => 12, 'BD_BigSmallTieGameID' => 13, 'BD_EvenOddGameID' => 14, 'BD_LowMiddleHighGameID' => 15, 'BD_NumberGameID' => 16),
            array('PID' => 12, 'portalProviderID' => 3, 'stockID' => 5, "payoutType" => 1, 'FD_BigSmallGameID' => 1, 'FD_EvenOddGameID' => 2, 'FD_LowMiddleHighGameID' => 3, 'FD_NumberGameID' => 4, 'LD_BigSmallGameID' => 5, 'LD_EvenOddGameID' => 6, 'LD_LowMiddleHighGameID' => 7, 'LD_NumberGameID' => 8, 'TD_BigSmallTieGameID' => 9, 'TD_EvenOddGameID' => 10, 'TD_LowMiddleHighGameID' => 11, 'TD_NumberGameID' => 12, 'BD_BigSmallTieGameID' => 13, 'BD_EvenOddGameID' => 14, 'BD_LowMiddleHighGameID' => 15, 'BD_NumberGameID' => 16),
            array('PID' => 13, 'portalProviderID' => 3, 'stockID' => 6, "payoutType" => 1, 'FD_BigSmallGameID' => 1, 'FD_EvenOddGameID' => 2, 'FD_LowMiddleHighGameID' => 3, 'FD_NumberGameID' => 4, 'LD_BigSmallGameID' => 5, 'LD_EvenOddGameID' => 6, 'LD_LowMiddleHighGameID' => 7, 'LD_NumberGameID' => 8, 'TD_BigSmallTieGameID' => 9, 'TD_EvenOddGameID' => 10, 'TD_LowMiddleHighGameID' => 11, 'TD_NumberGameID' => 12, 'BD_BigSmallTieGameID' => 13, 'BD_EvenOddGameID' => 14, 'BD_LowMiddleHighGameID' => 15, 'BD_NumberGameID' => 16),
            array('PID' => 14, 'portalProviderID' => 3, 'stockID' => 7, "payoutType" => 1, 'FD_BigSmallGameID' => 17, 'FD_EvenOddGameID' => 18, 'FD_LowMiddleHighGameID' => 19, 'FD_NumberGameID' => 20, 'LD_BigSmallGameID' => 21, 'LD_EvenOddGameID' => 22, 'LD_LowMiddleHighGameID' => 23, 'LD_NumberGameID' => 24, 'TD_BigSmallTieGameID' => 25, 'TD_EvenOddGameID' => 26, 'TD_LowMiddleHighGameID' => 27, 'TD_NumberGameID' => 28, 'BD_BigSmallTieGameID' => 29, 'BD_EvenOddGameID' => 30, 'BD_LowMiddleHighGameID' => 31, 'BD_NumberGameID' => 32),

            array('PID' => 15, 'portalProviderID' => 4, 'stockID' => 1, "payoutType" => 1, 'FD_BigSmallGameID' => 1, 'FD_EvenOddGameID' => 2, 'FD_LowMiddleHighGameID' => 3, 'FD_NumberGameID' => 4, 'LD_BigSmallGameID' => 5, 'LD_EvenOddGameID' => 6, 'LD_LowMiddleHighGameID' => 7, 'LD_NumberGameID' => 8, 'TD_BigSmallTieGameID' => 9, 'TD_EvenOddGameID' => 10, 'TD_LowMiddleHighGameID' => 11, 'TD_NumberGameID' => 12, 'BD_BigSmallTieGameID' => 13, 'BD_EvenOddGameID' => 14, 'BD_LowMiddleHighGameID' => 15, 'BD_NumberGameID' => 16),
            array('PID' => 16, 'portalProviderID' => 4, 'stockID' => 2, "payoutType" => 1, 'FD_BigSmallGameID' => 1, 'FD_EvenOddGameID' => 2, 'FD_LowMiddleHighGameID' => 3, 'FD_NumberGameID' => 4, 'LD_BigSmallGameID' => 5, 'LD_EvenOddGameID' => 6, 'LD_LowMiddleHighGameID' => 7, 'LD_NumberGameID' => 8, 'TD_BigSmallTieGameID' => 9, 'TD_EvenOddGameID' => 10, 'TD_LowMiddleHighGameID' => 11, 'TD_NumberGameID' => 12, 'BD_BigSmallTieGameID' => 13, 'BD_EvenOddGameID' => 14, 'BD_LowMiddleHighGameID' => 15, 'BD_NumberGameID' => 16),
            array('PID' => 17, 'portalProviderID' => 4, 'stockID' => 3, "payoutType" => 1, 'FD_BigSmallGameID' => 1, 'FD_EvenOddGameID' => 2, 'FD_LowMiddleHighGameID' => 3, 'FD_NumberGameID' => 4, 'LD_BigSmallGameID' => 5, 'LD_EvenOddGameID' => 6, 'LD_LowMiddleHighGameID' => 7, 'LD_NumberGameID' => 8, 'TD_BigSmallTieGameID' => 9, 'TD_EvenOddGameID' => 10, 'TD_LowMiddleHighGameID' => 11, 'TD_NumberGameID' => 12, 'BD_BigSmallTieGameID' => 13, 'BD_EvenOddGameID' => 14, 'BD_LowMiddleHighGameID' => 15, 'BD_NumberGameID' => 16),
            array('PID' => 18, 'portalProviderID' => 4, 'stockID' => 4, "payoutType" => 1, 'FD_BigSmallGameID' => 1, 'FD_EvenOddGameID' => 2, 'FD_LowMiddleHighGameID' => 3, 'FD_NumberGameID' => 4, 'LD_BigSmallGameID' => 5, 'LD_EvenOddGameID' => 6, 'LD_LowMiddleHighGameID' => 7, 'LD_NumberGameID' => 8, 'TD_BigSmallTieGameID' => 9, 'TD_EvenOddGameID' => 10, 'TD_LowMiddleHighGameID' => 11, 'TD_NumberGameID' => 12, 'BD_BigSmallTieGameID' => 13, 'BD_EvenOddGameID' => 14, 'BD_LowMiddleHighGameID' => 15, 'BD_NumberGameID' => 16),
            array('PID' => 19, 'portalProviderID' => 4, 'stockID' => 5, "payoutType" => 1, 'FD_BigSmallGameID' => 1, 'FD_EvenOddGameID' => 2, 'FD_LowMiddleHighGameID' => 3, 'FD_NumberGameID' => 4, 'LD_BigSmallGameID' => 5, 'LD_EvenOddGameID' => 6, 'LD_LowMiddleHighGameID' => 7, 'LD_NumberGameID' => 8, 'TD_BigSmallTieGameID' => 9, 'TD_EvenOddGameID' => 10, 'TD_LowMiddleHighGameID' => 11, 'TD_NumberGameID' => 12, 'BD_BigSmallTieGameID' => 13, 'BD_EvenOddGameID' => 14, 'BD_LowMiddleHighGameID' => 15, 'BD_NumberGameID' => 16),
            array('PID' => 20, 'portalProviderID' => 4, 'stockID' => 6, "payoutType" => 1, 'FD_BigSmallGameID' => 1, 'FD_EvenOddGameID' => 2, 'FD_LowMiddleHighGameID' => 3, 'FD_NumberGameID' => 4, 'LD_BigSmallGameID' => 5, 'LD_EvenOddGameID' => 6, 'LD_LowMiddleHighGameID' => 7, 'LD_NumberGameID' => 8, 'TD_BigSmallTieGameID' => 9, 'TD_EvenOddGameID' => 10, 'TD_LowMiddleHighGameID' => 11, 'TD_NumberGameID' => 12, 'BD_BigSmallTieGameID' => 13, 'BD_EvenOddGameID' => 14, 'BD_LowMiddleHighGameID' => 15, 'BD_NumberGameID' => 16),
            array('PID' => 21, 'portalProviderID' => 4, 'stockID' => 7, "payoutType" => 1, 'FD_BigSmallGameID' => 17, 'FD_EvenOddGameID' => 18, 'FD_LowMiddleHighGameID' => 19, 'FD_NumberGameID' => 20, 'LD_BigSmallGameID' => 21, 'LD_EvenOddGameID' => 22, 'LD_LowMiddleHighGameID' => 23, 'LD_NumberGameID' => 24, 'TD_BigSmallTieGameID' => 25, 'TD_EvenOddGameID' => 26, 'TD_LowMiddleHighGameID' => 27, 'TD_NumberGameID' => 28, 'BD_BigSmallTieGameID' => 29, 'BD_EvenOddGameID' => 30, 'BD_LowMiddleHighGameID' => 31, 'BD_NumberGameID' => 32),
        ];

        ProviderGameSetup::insert($providerGameSetup);
    }
}
