<?php

use Illuminate\Database\Seeder;
use App\Models\Country;


class countrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $country = array(
            array('countryName' => 'Afghanistan', 'alphaTwoCode' => 'AF', 'alphaThreeCode' => 'AFG', 'countryCode' => 4),
            array('countryName' => 'Albania', 'alphaTwoCode' => 'AL', 'alphaThreeCode' => 'ALB', 'countryCode' => 8),
            array('countryName' => 'Algeria', 'alphaTwoCode' => 'DZ', 'alphaThreeCode' => 'DZA', 'countryCode' => 12),
            array('countryName' => 'American Samoa', 'alphaTwoCode' => 'AS', 'alphaThreeCode' => 'ASM', 'countryCode' => 16),
            array('countryName' => 'Andorra', 'alphaTwoCode' => 'AD', 'alphaThreeCode' => 'AND', 'countryCode'=>20),
            array('countryName' => 'Angola', 'alphaTwoCode' => 'AO', 'alphaThreeCode' => 'AGO', 'countryCode' => 24),
            array('countryName' => 'Anguilla', 'alphaTwoCode' => 'AI', 'alphaThreeCode' => 'AIA', 'countryCode' => 660),
            array('countryName' => 'Antarctica', 'alphaTwoCode' => 'AQ', 'alphaThreeCode' => 'ATA', 'countryCode' => 10),
            array('countryName' => 'Antigua and Barbuda', 'alphaTwoCode' => 'AG', 'alphaThreeCode' => 'ATG', 'countryCode' => 28),
            array('countryName' => 'Argentina', 'alphaTwoCode' => 'AR', 'alphaThreeCode' => 'ARG', 'countryCode' => 32),
            array('countryName' => 'Armenia', 'alphaTwoCode' => 'AM', 'alphaThreeCode' => 'ARM', 'countryCode' => 51),
            array('countryName' => 'Aruba', 'alphaTwoCode' => 'AW', 'alphaThreeCode' => 'ABW', 'countryCode' => 533),
            array('countryName' => 'Australia', 'alphaTwoCode' => 'AU', 'alphaThreeCode' => 'AUS', 'countryCode' => 36),
            array('countryName' => 'Austria', 'alphaTwoCode' => 'AT', 'alphaThreeCode' => 'AUT', 'countryCode' => 40),
            array('countryName' => 'Azerbaijan', 'alphaTwoCode' => 'AZ', 'alphaThreeCode' => 'AZE', 'countryCode' => 31),
            array('countryName' => 'Bahamas (the)', 'alphaTwoCode' => 'BS', 'alphaThreeCode' => 'BHS', 'countryCode' => 44),
            array('countryName' => 'Bahrain', 'alphaTwoCode' => 'BH', 'alphaThreeCode' => 'BHR', 'countryCode' => 48),
            array('countryName' => 'Bangladesh', 'alphaTwoCode' => 'BD', 'alphaThreeCode' => 'BGD', 'countryCode' => 50),
            array('countryName' => 'Barbados', 'alphaTwoCode' => 'BB', 'alphaThreeCode' => 'BRB', 'countryCode' => 52),
            array('countryName' => 'Belarus', 'alphaTwoCode' => 'BY', 'alphaThreeCode' => 'BLR', 'countryCode' => 112),
            array('countryName' => 'Belgium', 'alphaTwoCode' => 'BE', 'alphaThreeCode' => 'BEL', 'countryCode' => 56),
            array('countryName' => 'Belize', 'alphaTwoCode' => 'BZ', 'alphaThreeCode' => 'BLZ', 'countryCode' => 84),
            array('countryName' => 'Benin', 'alphaTwoCode' => 'BJ', 'alphaThreeCode' => 'BEN', 'countryCode' => 204),
            array('countryName' => 'Bermuda', 'alphaTwoCode' => 'BM', 'alphaThreeCode' => 'BMU', 'countryCode' => 60),
            array('countryName' => 'Bhutan', 'alphaTwoCode' => 'BT', 'alphaThreeCode' => 'BTN', 'countryCode' => 64),
            array('countryName' => 'Bolivia (Plurinational State of)', 'alphaTwoCode' => 'BO', 'alphaThreeCode' => 'BOL', 'countryCode' => 68),
            array('countryName' => 'Bonaire, Sint Eustatius and Saba', 'alphaTwoCode' => 'BQ', 'alphaThreeCode' => 'BES', 'countryCode' => 535),
            array('countryName' => 'Bosnia and Herzegovina', 'alphaTwoCode' => 'BA', 'alphaThreeCode' => 'BIH', 'countryCode' => 70),
            array('countryName' => 'Botswana', 'alphaTwoCode' => 'BW', 'alphaThreeCode' => 'BWA', 'countryCode' => 72),
            array('countryName' => 'Bouvet Island', 'alphaTwoCode' => 'BV', 'alphaThreeCode' => 'BVT', 'countryCode' => 74),
            array('countryName' => 'Brazil', 'alphaTwoCode' => 'BR', 'alphaThreeCode' => 'BRA', 'countryCode' => 76),
            array('countryName' => 'British Indian Ocean Territory (the)', 'alphaTwoCode' => 'IO', 'alphaThreeCode' => 'IOT', 'countryCode' => 86),
            array('countryName' => 'Brunei Darussalam', 'alphaTwoCode' => 'BN', 'alphaThreeCode' => 'BRN', 'countryCode' => 96),
            array('countryName' => 'Bulgaria', 'alphaTwoCode' => 'BG', 'alphaThreeCode' => 'BGR', 'countryCode' => 100),
            array('countryName' => 'Burkina Faso', 'alphaTwoCode' => 'BF', 'alphaThreeCode' => 'BFA', 'countryCode' => 854),
            array('countryName' => 'Burundi', 'alphaTwoCode' => 'BI', 'alphaThreeCode' => 'BDI', 'countryCode' => 108),
            array('countryName' => 'Cabo Verde', 'alphaTwoCode' => 'CV', 'alphaThreeCode' => 'CPV', 'countryCode' => 132),
            array('countryName' => 'Cambodia', 'alphaTwoCode' => 'KH', 'alphaThreeCode' => 'KHM', 'countryCode' => 116),
            array('countryName' => 'Cameroon', 'alphaTwoCode' => 'CM', 'alphaThreeCode' => 'CMR', 'countryCode' => 120),
            array('countryName' => 'Canada', 'alphaTwoCode' => 'CA', 'alphaThreeCode' => 'CAN', 'countryCode' => 124),
            array('countryName' => 'Cayman Islands (the)', 'alphaTwoCode' => 'KY', 'alphaThreeCode' => 'CYM', 'countryCode' => 136),
            array('countryName' => 'Central African Republic (the)', 'alphaTwoCode' => 'CF', 'alphaThreeCode' => 'CAF', 'countryCode' => 140),
            array('countryName' => 'Chad', 'alphaTwoCode' => 'TD', 'alphaThreeCode' => 'TCD', 'countryCode' => 148),
            array('countryName' => 'Chile', 'alphaTwoCode' => 'CL', 'alphaThreeCode' => 'CHL', 'countryCode' => 152),
            array('countryName' => 'China', 'alphaTwoCode' => 'CN', 'alphaThreeCode' => 'CHN', 'countryCode' => 156),
            array('countryName' => 'Christmas Island', 'alphaTwoCode' => 'CX', 'alphaThreeCode' => 'CXR', 'countryCode' => 162),
            array('countryName' => 'Cocos (Keeling) Islands (the)', 'alphaTwoCode' => 'CC', 'alphaThreeCode' => 'CCK', 'countryCode' => 166),
            array('countryName' => 'Colombia', 'alphaTwoCode' => 'CO', 'alphaThreeCode' => 'COL', 'countryCode' => 170),
            array('countryName' => 'Comoros (the)', 'alphaTwoCode' => 'KM', 'alphaThreeCode' => 'COM', 'countryCode' => 174),
            array('countryName' => 'Congo (the Democratic Republic of the)', 'alphaTwoCode' => 'CD', 'alphaThreeCode' => 'COD', 'countryCode' => 180),
            array('countryName' => 'Congo (the)', 'alphaTwoCode' => 'CG', 'alphaThreeCode' => 'COG', 'countryCode' => 178),
            array('countryName' => 'Cook Islands (the)', 'alphaTwoCode' => 'CK', 'alphaThreeCode' => 'COK', 'countryCode' => 184),
            array('countryName' => 'Costa Rica', 'alphaTwoCode' => 'CR', 'alphaThreeCode' => 'CRI', 'countryCode' => 188),
            array('countryName' => 'Croatia', 'alphaTwoCode' => 'HR', 'alphaThreeCode' => 'HRV', 'countryCode' => 191),
            array('countryName' => 'Cuba', 'alphaTwoCode' => 'CU', 'alphaThreeCode' => 'CUB', 'countryCode' => 192),
            array('countryName' => 'Curaçao', 'alphaTwoCode' => 'CW', 'alphaThreeCode' => 'CUW', 'countryCode' => 531),
            array('countryName' => 'Cyprus', 'alphaTwoCode' => 'CY', 'alphaThreeCode' => 'CYP', 'countryCode' => 196),
            array('countryName' => 'Czechia', 'alphaTwoCode' => 'CZ', 'alphaThreeCode' => 'CZE', 'countryCode' => 203),
            array('countryName' => 'Côte d\'Ivoire', 'alphaTwoCode' => 'CI', 'alphaThreeCode' => 'CIV', 'countryCode' => 384),
            array('countryName' => 'Denmark', 'alphaTwoCode' => 'DK', 'alphaThreeCode' => 'DNK', 'countryCode' => 208),
            array('countryName' => 'Djibouti', 'alphaTwoCode' => 'DJ', 'alphaThreeCode' => 'DJI', 'countryCode' => 262),
            array('countryName' => 'Dominica', 'alphaTwoCode' => 'DM', 'alphaThreeCode' => 'DMA', 'countryCode' => 212),
            array('countryName' => 'Dominican Republic (the)', 'alphaTwoCode' => 'DO', 'alphaThreeCode' => 'DOM', 'countryCode' => 214),
            array('countryName' => 'Ecuador', 'alphaTwoCode' => 'EC', 'alphaThreeCode' => 'ECU', 'countryCode' => 218),
            array('countryName' => 'Egypt', 'alphaTwoCode' => 'EG', 'alphaThreeCode' => 'EGY', 'countryCode' => 818),
            array('countryName' => 'El Salvador', 'alphaTwoCode' => 'SV', 'alphaThreeCode' => 'SLV', 'countryCode' => 222),
            array('countryName' => 'Equatorial Guinea', 'alphaTwoCode' => 'GQ', 'alphaThreeCode' => 'GNQ', 'countryCode' => 226),
            array('countryName' => 'Eritrea', 'alphaTwoCode' => 'ER', 'alphaThreeCode' => 'ERI', 'countryCode' => 232),
            array('countryName' => 'Estonia', 'alphaTwoCode' => 'EE', 'alphaThreeCode' => 'EST', 'countryCode' => 233),
            array('countryName' => 'Eswatini', 'alphaTwoCode' => 'SZ', 'alphaThreeCode' => 'SWZ', 'countryCode' => 748),
            array('countryName' => 'Ethiopia', 'alphaTwoCode' => 'ET', 'alphaThreeCode' => 'ETH', 'countryCode' => 231),
            array('countryName' => 'Falkland Islands (the) [Malvinas]', 'alphaTwoCode' => 'FK', 'alphaThreeCode' => 'FLK', 'countryCode' => 238),
            array('countryName' => 'Faroe Islands (the)', 'alphaTwoCode' => 'FO', 'alphaThreeCode' => 'FRO', 'countryCode' => 234),
            array('countryName' => 'Fiji', 'alphaTwoCode' => 'FJ', 'alphaThreeCode' => 'FJI', 'countryCode' => 242),
            array('countryName' => 'Finland', 'alphaTwoCode' => 'FI', 'alphaThreeCode' => 'FIN', 'countryCode' => 246),
            array('countryName' => 'France', 'alphaTwoCode' => 'FR', 'alphaThreeCode' => 'FRA', 'countryCode' => 250),
            array('countryName' => 'French Guiana', 'alphaTwoCode' => 'GF', 'alphaThreeCode' => 'GUF', 'countryCode' => 254),
            array('countryName' => 'French Polynesia', 'alphaTwoCode' => 'PF', 'alphaThreeCode' => 'PYF', 'countryCode' => 258),
            array('countryName' => 'French Southern Territories (the)', 'alphaTwoCode' => 'TF', 'alphaThreeCode' => 'ATF', 'countryCode' => 260),
            array('countryName' => 'Gabon', 'alphaTwoCode' => 'GA', 'alphaThreeCode' => 'GAB', 'countryCode' => 266),
            array('countryName' => 'Gambia (the)', 'alphaTwoCode' => 'GM', 'alphaThreeCode' => 'GMB', 'countryCode' => 270),
            array('countryName' => 'Georgia', 'alphaTwoCode' => 'GE', 'alphaThreeCode' => 'GEO', 'countryCode' => 268),
            array('countryName' => 'Germany', 'alphaTwoCode' => 'DE', 'alphaThreeCode' => 'DEU', 'countryCode' => 276),
            array('countryName' => 'Ghana', 'alphaTwoCode' => 'GH', 'alphaThreeCode' => 'GHA', 'countryCode' => 288),
            array('countryName' => 'Gibraltar', 'alphaTwoCode' => 'GI', 'alphaThreeCode' => 'GIB', 'countryCode' => 292),
            array('countryName' => 'Greece', 'alphaTwoCode' => 'GR', 'alphaThreeCode' => 'GRC', 'countryCode' => 300),
            array('countryName' => 'Greenland', 'alphaTwoCode' => 'GL', 'alphaThreeCode' => 'GRL', 'countryCode' => 304),
            array('countryName' => 'Grenada', 'alphaTwoCode' => 'GD', 'alphaThreeCode' => 'GRD', 'countryCode' => 308),
            array('countryName' => 'Guadeloupe', 'alphaTwoCode' => 'GP', 'alphaThreeCode' => 'GLP', 'countryCode' => 312),
            array('countryName' => 'Guam', 'alphaTwoCode' => 'GU', 'alphaThreeCode' => 'GUM', 'countryCode' => 316),
            array('countryName' => 'Guatemala', 'alphaTwoCode' => 'GT', 'alphaThreeCode' => 'GTM', 'countryCode' => 320),
            array('countryName' => 'Guernsey', 'alphaTwoCode' => 'GG', 'alphaThreeCode' => 'GGY', 'countryCode' => 831),
            array('countryName' => 'Guinea', 'alphaTwoCode' => 'GN', 'alphaThreeCode' => 'GIN', 'countryCode' => 324),
            array('countryName' => 'Guinea-Bissau', 'alphaTwoCode' => 'GW', 'alphaThreeCode' => 'GNB', 'countryCode' => 624),
            array('countryName' => 'Guyana', 'alphaTwoCode' => 'GY', 'alphaThreeCode' => 'GUY', 'countryCode' => 328),
            array('countryName' => 'Haiti', 'alphaTwoCode' => 'HT', 'alphaThreeCode' => 'HTI', 'countryCode' => 332),
            array('countryName' => 'Heard Island and McDonald Islands', 'alphaTwoCode' => 'HM', 'alphaThreeCode' => 'HMD', 'countryCode' => 334),
            array('countryName' => 'Holy See (the)', 'alphaTwoCode' => 'VA', 'alphaThreeCode' => 'VAT', 'countryCode' => 336),
            array('countryName' => 'Honduras', 'alphaTwoCode' => 'HN', 'alphaThreeCode' => 'HND', 'countryCode' => 340),
            array('countryName' => 'Hong Kong', 'alphaTwoCode' => 'HK', 'alphaThreeCode' => 'HKG', 'countryCode' => 344),
            array('countryName' => 'Hungary', 'alphaTwoCode' => 'HU', 'alphaThreeCode' => 'HUN', 'countryCode' => 348),
            array('countryName' => 'Iceland', 'alphaTwoCode' => 'IS', 'alphaThreeCode' => 'ISL', 'countryCode' => 352),
            array('countryName' => 'India', 'alphaTwoCode' => 'IN', 'alphaThreeCode' => 'IND', 'countryCode' => 356),
            array('countryName' => 'Indonesia', 'alphaTwoCode' => 'ID', 'alphaThreeCode' => 'IDN', 'countryCode' => 360),
            array('countryName' => 'Iran (Islamic Republic of)', 'alphaTwoCode' => 'IR', 'alphaThreeCode' => 'IRN', 'countryCode' => 364),
            array('countryName' => 'Iraq', 'alphaTwoCode' => 'IQ', 'alphaThreeCode' => 'IRQ', 'countryCode' => 368),
            array('countryName' => 'Ireland', 'alphaTwoCode' => 'IE', 'alphaThreeCode' => 'IRL', 'countryCode' => 372),
            array('countryName' => 'Isle of Man', 'alphaTwoCode' => 'IM', 'alphaThreeCode' => 'IMN', 'countryCode' => 833),
            array('countryName' => 'Israel', 'alphaTwoCode' => 'IL', 'alphaThreeCode' => 'ISR', 'countryCode' => 376),
            array('countryName' => 'Italy', 'alphaTwoCode' => 'IT', 'alphaThreeCode' => 'ITA', 'countryCode' => 380),
            array('countryName' => 'Jamaica', 'alphaTwoCode' => 'JM', 'alphaThreeCode' => 'JAM', 'countryCode' => 388),
            array('countryName' => 'Japan', 'alphaTwoCode' => 'JP', 'alphaThreeCode' => 'JPN', 'countryCode' => 392),
            array('countryName' => 'Jersey', 'alphaTwoCode' => 'JE', 'alphaThreeCode' => 'JEY', 'countryCode' => 832),
            array('countryName' => 'Jordan', 'alphaTwoCode' => 'JO', 'alphaThreeCode' => 'JOR', 'countryCode' => 400),
            array('countryName' => 'Kazakhstan', 'alphaTwoCode' => 'KZ', 'alphaThreeCode' => 'KAZ', 'countryCode' => 398),
            array('countryName' => 'Kenya', 'alphaTwoCode' => 'KE', 'alphaThreeCode' => 'KEN', 'countryCode' => 404),
            array('countryName' => 'Kiribati', 'alphaTwoCode' => 'KI', 'alphaThreeCode' => 'KIR', 'countryCode' => 296),
            array('countryName' => 'Korea (the Democratic People\'s Republic of)', 'alphaTwoCode' => 'KP', 'alphaThreeCode' => 'PRK', 'countryCode' => 408),
            array('countryName' => 'Korea (the Republic of)', 'alphaTwoCode' => 'KR', 'alphaThreeCode' => 'KOR', 'countryCode' => 410),
            array('countryName' => 'Kuwait', 'alphaTwoCode' => 'KW', 'alphaThreeCode' => 'KWT', 'countryCode' => 414),
            array('countryName' => 'Kyrgyzstan', 'alphaTwoCode' => 'KG', 'alphaThreeCode' => 'KGZ', 'countryCode' => 417),
            array('countryName' => 'Lao People\'s Democratic Republic (the)', 'alphaTwoCode' => 'LA', 'alphaThreeCode' => 'LAO', 'countryCode' => 418),
            array('countryName' => 'Latvia', 'alphaTwoCode' => 'LV', 'alphaThreeCode' => 'LVA', 'countryCode' => 428),
            array('countryName' => 'Lebanon', 'alphaTwoCode' => 'LB', 'alphaThreeCode' => 'LBN', 'countryCode' => 422),
            array('countryName' => 'Lesotho', 'alphaTwoCode' => 'LS', 'alphaThreeCode' => 'LSO', 'countryCode' => 426),
            array('countryName' => 'Liberia', 'alphaTwoCode' => 'LR', 'alphaThreeCode' => 'LBR', 'countryCode' => 430),
            array('countryName' => 'Libya', 'alphaTwoCode' => 'LY', 'alphaThreeCode' => 'LBY', 'countryCode' => 434),
            array('countryName' => 'Liechtenstein', 'alphaTwoCode' => 'LI', 'alphaThreeCode' => 'LIE', 'countryCode' => 438),
            array('countryName' => 'Lithuania', 'alphaTwoCode' => 'LT', 'alphaThreeCode' => 'LTU', 'countryCode' => 440),
            array('countryName' => 'Luxembourg', 'alphaTwoCode' => 'LU', 'alphaThreeCode' => 'LUX', 'countryCode' => 442),
            array('countryName' => 'Macao', 'alphaTwoCode' => 'MO', 'alphaThreeCode' => 'MAC', 'countryCode' => 446),
            array('countryName' => 'Madagascar', 'alphaTwoCode' => 'MG', 'alphaThreeCode' => 'MDG', 'countryCode' => 450),
            array('countryName' => 'Malawi', 'alphaTwoCode' => 'MW', 'alphaThreeCode' => 'MWI', 'countryCode' => 454),
            array('countryName' => 'Malaysia', 'alphaTwoCode' => 'MY', 'alphaThreeCode' => 'MYS', 'countryCode' => 458),
            array('countryName' => 'Maldives', 'alphaTwoCode' => 'MV', 'alphaThreeCode' => 'MDV', 'countryCode' => 462),
            array('countryName' => 'Mali', 'alphaTwoCode' => 'ML', 'alphaThreeCode' => 'MLI', 'countryCode' => 466),
            array('countryName' => 'Malta', 'alphaTwoCode' => 'MT', 'alphaThreeCode' => 'MLT', 'countryCode' => 470),
            array('countryName' => 'Marshall Islands (the)', 'alphaTwoCode' => 'MH', 'alphaThreeCode' => 'MHL', 'countryCode' => 584),
            array('countryName' => 'Martinique', 'alphaTwoCode' => 'MQ', 'alphaThreeCode' => 'MTQ', 'countryCode' => 474),
            array('countryName' => 'Mauritania', 'alphaTwoCode' => 'MR', 'alphaThreeCode' => 'MRT', 'countryCode' => 478),
            array('countryName' => 'Mauritius', 'alphaTwoCode' => 'MU', 'alphaThreeCode' => 'MUS', 'countryCode' => 480),
            array('countryName' => 'Mayotte', 'alphaTwoCode' => 'YT', 'alphaThreeCode' => 'MYT', 'countryCode' => 175),
            array('countryName' => 'Mexico', 'alphaTwoCode' => 'MX', 'alphaThreeCode' => 'MEX', 'countryCode' => 484),
            array('countryName' => 'Micronesia (Federated States of)', 'alphaTwoCode' => 'FM', 'alphaThreeCode' => 'FSM', 'countryCode' => 583),
            array('countryName' => 'Moldova (the Republic of)', 'alphaTwoCode' => 'MD', 'alphaThreeCode' => 'MDA', 'countryCode' => 498),
            array('countryName' => 'Monaco', 'alphaTwoCode' => 'MC', 'alphaThreeCode' => 'MCO', 'countryCode' => 492),
            array('countryName' => 'Mongolia', 'alphaTwoCode' => 'MN', 'alphaThreeCode' => 'MNG', 'countryCode' => 496),
            array('countryName' => 'Montenegro', 'alphaTwoCode' => 'ME', 'alphaThreeCode' => 'MNE', 'countryCode' => 499),
            array('countryName' => 'Montserrat', 'alphaTwoCode' => 'MS', 'alphaThreeCode' => 'MSR', 'countryCode' => 500),
            array('countryName' => 'Morocco', 'alphaTwoCode' => 'MA', 'alphaThreeCode' => 'MAR', 'countryCode' => 504),
            array('countryName' => 'Mozambique', 'alphaTwoCode' => 'MZ', 'alphaThreeCode' => 'MOZ', 'countryCode' => 508),
            array('countryName' => 'Myanmar', 'alphaTwoCode' => 'MM', 'alphaThreeCode' => 'MMR', 'countryCode' => 104),
            array('countryName' => 'Namibia', 'alphaTwoCode' => 'NA', 'alphaThreeCode' => 'NAM', 'countryCode' => 516),
            array('countryName' => 'Nauru', 'alphaTwoCode' => 'NR', 'alphaThreeCode' => 'NRU', 'countryCode' => 520),
            array('countryName' => 'Nepal', 'alphaTwoCode' => 'NP', 'alphaThreeCode' => 'NPL', 'countryCode' => 524),
            array('countryName' => 'Netherlands (the)', 'alphaTwoCode' => 'NL', 'alphaThreeCode' => 'NLD', 'countryCode' => 528),
            array('countryName' => 'New Caledonia', 'alphaTwoCode' => 'NC', 'alphaThreeCode' => 'NCL', 'countryCode' => 540),
            array('countryName' => 'New Zealand', 'alphaTwoCode' => 'NZ', 'alphaThreeCode' => 'NZL', 'countryCode' => 554),
            array('countryName' => 'Nicaragua', 'alphaTwoCode' => 'NI', 'alphaThreeCode' => 'NIC', 'countryCode' => 558),
            array('countryName' => 'Niger (the)', 'alphaTwoCode' => 'NE', 'alphaThreeCode' => 'NER', 'countryCode' => 562),
            array('countryName' => 'Nigeria', 'alphaTwoCode' => 'NG', 'alphaThreeCode' => 'NGA', 'countryCode' => 566),
            array('countryName' => 'Niue', 'alphaTwoCode' => 'NU', 'alphaThreeCode' => 'NIU', 'countryCode' => 570),
            array('countryName' => 'Norfolk Island', 'alphaTwoCode' => 'NF', 'alphaThreeCode' => 'NFK', 'countryCode' => 574),
            array('countryName' => 'Northern Mariana Islands (the)', 'alphaTwoCode' => 'MP', 'alphaThreeCode' => 'MNP', 'countryCode' => 580),
            array('countryName' => 'Norway', 'alphaTwoCode' => 'NO', 'alphaThreeCode' => 'NOR', 'countryCode' => 578),
            array('countryName' => 'Oman', 'alphaTwoCode' => 'OM', 'alphaThreeCode' => 'OMN', 'countryCode' => 512),
            array('countryName' => 'Pakistan', 'alphaTwoCode' => 'PK', 'alphaThreeCode' => 'PAK', 'countryCode' => 586),
            array('countryName' => 'Palau', 'alphaTwoCode' => 'PW', 'alphaThreeCode' => 'PLW', 'countryCode' => 585),
            array('countryName' => 'Palestine, State of', 'alphaTwoCode' => 'PS', 'alphaThreeCode' => 'PSE', 'countryCode' => 275),
            array('countryName' => 'Panama', 'alphaTwoCode' => 'PA', 'alphaThreeCode' => 'PAN', 'countryCode' => 591),
            array('countryName' => 'Papua New Guinea', 'alphaTwoCode' => 'PG', 'alphaThreeCode' => 'PNG', 'countryCode' => 598),
            array('countryName' => 'Paraguay', 'alphaTwoCode' => 'PY', 'alphaThreeCode' => 'PRY', 'countryCode' => 600),
            array('countryName' => 'Peru', 'alphaTwoCode' => 'PE', 'alphaThreeCode' => 'PER', 'countryCode' => 604),
            array('countryName' => 'Philippines (the)', 'alphaTwoCode' => 'PH', 'alphaThreeCode' => 'PHL', 'countryCode' => 608),
            array('countryName' => 'Pitcairn', 'alphaTwoCode' => 'PN', 'alphaThreeCode' => 'PCN', 'countryCode' => 612),
            array('countryName' => 'Poland', 'alphaTwoCode' => 'PL', 'alphaThreeCode' => 'POL', 'countryCode' => 616),
            array('countryName' => 'Portugal', 'alphaTwoCode' => 'PT', 'alphaThreeCode' => 'PRT', 'countryCode' => 620),
            array('countryName' => 'Puerto Rico', 'alphaTwoCode' => 'PR', 'alphaThreeCode' => 'PRI', 'countryCode' => 630),
            array('countryName' => 'Qatar', 'alphaTwoCode' => 'QA', 'alphaThreeCode' => 'QAT', 'countryCode' => 634),
            array('countryName' => 'Republic of North Macedonia', 'alphaTwoCode' => 'MK', 'alphaThreeCode' => 'MKD', 'countryCode' => 807),
            array('countryName' => 'Romania', 'alphaTwoCode' => 'RO', 'alphaThreeCode' => 'ROU', 'countryCode' => 642),
            array('countryName' => 'Russian Federation (the)', 'alphaTwoCode' => 'RU', 'alphaThreeCode' => 'RUS', 'countryCode' => 643),
            array('countryName' => 'Rwanda', 'alphaTwoCode' => 'RW', 'alphaThreeCode' => 'RWA', 'countryCode' => 646),
            array('countryName' => 'Réunion', 'alphaTwoCode' => 'RE', 'alphaThreeCode' => 'REU', 'countryCode' => 638),
            array('countryName' => 'Saint Barthélemy', 'alphaTwoCode' => 'BL', 'alphaThreeCode' => 'BLM', 'countryCode' => 652),
            array('countryName' => 'Saint Helena, Ascension and Tristan da Cunha', 'alphaTwoCode' => 'SH', 'alphaThreeCode' => 'SHN', 'countryCode' => 654),
            array('countryName' => 'Saint Kitts and Nevis', 'alphaTwoCode' => 'KN', 'alphaThreeCode' => 'KNA', 'countryCode' => 659),
            array('countryName' => 'Saint Lucia', 'alphaTwoCode' => 'LC', 'alphaThreeCode' => 'LCA', 'countryCode' => 662),
            array('countryName' => 'Saint Martin (French part)', 'alphaTwoCode' => 'MF', 'alphaThreeCode' => 'MAF', 'countryCode' => 663),
            array('countryName' => 'Saint Pierre and Miquelon', 'alphaTwoCode' => 'PM', 'alphaThreeCode' => 'SPM', 'countryCode' => 666),
            array('countryName' => 'Saint Vincent and the Grenadines', 'alphaTwoCode' => 'VC', 'alphaThreeCode' => 'VCT', 'countryCode' => 670),
            array('countryName' => 'Samoa', 'alphaTwoCode' => 'WS', 'alphaThreeCode' => 'WSM', 'countryCode' => 882),
            array('countryName' => 'San Marino', 'alphaTwoCode' => 'SM', 'alphaThreeCode' => 'SMR', 'countryCode' => 674),
            array('countryName' => 'Sao Tome and Principe', 'alphaTwoCode' => 'ST', 'alphaThreeCode' => 'STP', 'countryCode' => 678),
            array('countryName' => 'Saudi Arabia', 'alphaTwoCode' => 'SA', 'alphaThreeCode' => 'SAU', 'countryCode' => 682),
            array('countryName' => 'Senegal', 'alphaTwoCode' => 'SN', 'alphaThreeCode' => 'SEN', 'countryCode' => 686),
            array('countryName' => 'Serbia', 'alphaTwoCode' => 'RS', 'alphaThreeCode' => 'SRB', 'countryCode' => 688),
            array('countryName' => 'Seychelles', 'alphaTwoCode' => 'SC', 'alphaThreeCode' => 'SYC', 'countryCode' => 690),
            array('countryName' => 'Sierra Leone', 'alphaTwoCode' => 'SL', 'alphaThreeCode' => 'SLE', 'countryCode' => 694),
            array('countryName' => 'Singapore', 'alphaTwoCode' => 'SG', 'alphaThreeCode' => 'SGP', 'countryCode' => 702),
            array('countryName' => 'Sint Maarten (Dutch part)', 'alphaTwoCode' => 'SX', 'alphaThreeCode' => 'SXM', 'countryCode' => 534),
            array('countryName' => 'Slovakia', 'alphaTwoCode' => 'SK', 'alphaThreeCode' => 'SVK', 'countryCode' => 703),
            array('countryName' => 'Slovenia', 'alphaTwoCode' => 'SI', 'alphaThreeCode' => 'SVN', 'countryCode' => 705),
            array('countryName' => 'Solomon Islands', 'alphaTwoCode' => 'SB', 'alphaThreeCode' => 'SLB', 'countryCode' => 90),
            array('countryName' => 'Somalia', 'alphaTwoCode' => 'SO', 'alphaThreeCode' => 'SOM', 'countryCode' => 706),
            array('countryName' => 'South Africa', 'alphaTwoCode' => 'ZA', 'alphaThreeCode' => 'ZAF', 'countryCode' => 710),
            array('countryName' => 'South Georgia and the South Sandwich Islands', 'alphaTwoCode' => 'GS', 'alphaThreeCode' => 'SGS', 'countryCode' => 239),
            array('countryName' => 'South Sudan', 'alphaTwoCode' => 'SS', 'alphaThreeCode' => 'SSD', 'countryCode' => 728),
            array('countryName' => 'Spain', 'alphaTwoCode' => 'ES', 'alphaThreeCode' => 'ESP', 'countryCode' => 724),
            array('countryName' => 'Sri Lanka', 'alphaTwoCode' => 'LK', 'alphaThreeCode' => 'LKA', 'countryCode' => 144),
            array('countryName' => 'Sudan (the)', 'alphaTwoCode' => 'SD', 'alphaThreeCode' => 'SDN', 'countryCode' => 729),
            array('countryName' => 'Suriname', 'alphaTwoCode' => 'SR', 'alphaThreeCode' => 'SUR', 'countryCode' => 740),
            array('countryName' => 'Svalbard and Jan Mayen', 'alphaTwoCode' => 'SJ', 'alphaThreeCode' => 'SJM', 'countryCode' => 744),
            array('countryName' => 'Sweden', 'alphaTwoCode' => 'SE', 'alphaThreeCode' => 'SWE', 'countryCode' => 752),
            array('countryName' => 'Switzerland', 'alphaTwoCode' => 'CH', 'alphaThreeCode' => 'CHE', 'countryCode' => 756),
            array('countryName' => 'Syrian Arab Republic', 'alphaTwoCode' => 'SY', 'alphaThreeCode' => 'SYR', 'countryCode' => 760),
            array('countryName' => 'Taiwan (Province of China)', 'alphaTwoCode' => 'TW', 'alphaThreeCode' => 'TWN', 'countryCode' => 158),
            array('countryName' => 'Tajikistan', 'alphaTwoCode' => 'TJ', 'alphaThreeCode' => 'TJK', 'countryCode' => 762),
            array('countryName' => 'Tanzania, United Republic of', 'alphaTwoCode' => 'TZ', 'alphaThreeCode' => 'TZA', 'countryCode' => 834),
            array('countryName' => 'Thailand', 'alphaTwoCode' => 'TH', 'alphaThreeCode' => 'THA', 'countryCode' => 764),
            array('countryName' => 'Timor-Leste', 'alphaTwoCode' => 'TL', 'alphaThreeCode' => 'TLS', 'countryCode' => 626),
            array('countryName' => 'Togo', 'alphaTwoCode' => 'TG', 'alphaThreeCode' => 'TGO', 'countryCode' => 768),
            array('countryName' => 'Tokelau', 'alphaTwoCode' => 'TK', 'alphaThreeCode' => 'TKL', 'countryCode' => 772),
            array('countryName' => 'Tonga', 'alphaTwoCode' => 'TO', 'alphaThreeCode' => 'TON', 'countryCode' => 776),
            array('countryName' => 'Trinidad and Tobago', 'alphaTwoCode' => 'TT', 'alphaThreeCode' => 'TTO', 'countryCode' => 780),
            array('countryName' => 'Tunisia', 'alphaTwoCode' => 'TN', 'alphaThreeCode' => 'TUN', 'countryCode' => 788),
            array('countryName' => 'Turkey', 'alphaTwoCode' => 'TR', 'alphaThreeCode' => 'TUR', 'countryCode' => 792),
            array('countryName' => 'Turkmenistan', 'alphaTwoCode' => 'TM', 'alphaThreeCode' => 'TKM', 'countryCode' => 795),
            array('countryName' => 'Turks and Caicos Islands (the)', 'alphaTwoCode' => 'TC', 'alphaThreeCode' => 'TCA', 'countryCode' => 796),
            array('countryName' => 'Tuvalu', 'alphaTwoCode' => 'TV', 'alphaThreeCode' => 'TUV', 'countryCode' => 798),
            array('countryName' => 'Uganda', 'alphaTwoCode' => 'UG', 'alphaThreeCode' => 'UGA', 'countryCode' => 800),
            array('countryName' => 'Ukraine', 'alphaTwoCode' => 'UA', 'alphaThreeCode' => 'UKR', 'countryCode' => 804),
            array('countryName' => 'United Arab Emirates (the)', 'alphaTwoCode' => 'AE', 'alphaThreeCode' => 'ARE', 'countryCode' => 784),
            array('countryName' => 'United Kingdom of Great Britain and Northern Ireland (the)', 'alphaTwoCode' => 'GB', 'alphaThreeCode' => 'GBR', 'countryCode' => 826),
            array('countryName' => 'United States Minor Outlying Islands (the)', 'alphaTwoCode' => 'UM', 'alphaThreeCode' => 'UMI', 'countryCode' => 581),
            array('countryName' => 'United States of America (the)', 'alphaTwoCode' => 'US', 'alphaThreeCode' => 'USA', 'countryCode' => 840),
            array('countryName' => 'Uruguay', 'alphaTwoCode' => 'UY', 'alphaThreeCode' => 'URY', 'countryCode' => 858),
            array('countryName' => 'Uzbekistan', 'alphaTwoCode' => 'UZ', 'alphaThreeCode' => 'UZB', 'countryCode' => 860),
            array('countryName' => 'Vanuatu', 'alphaTwoCode' => 'VU', 'alphaThreeCode' => 'VUT', 'countryCode' => 548),
            array('countryName' => 'Venezuela (Bolivarian Republic of)', 'alphaTwoCode' => 'VE', 'alphaThreeCode' => 'VEN', 'countryCode' => 862),
            array('countryName' => 'Viet Nam', 'alphaTwoCode' => 'VN', 'alphaThreeCode' => 'VNM', 'countryCode' => 704),
            array('countryName' => 'Virgin Islands (British)', 'alphaTwoCode' => 'VG', 'alphaThreeCode' => 'VGB', 'countryCode' => 92),
            array('countryName' => 'Virgin Islands (U.S.)', 'alphaTwoCode' => 'VI', 'alphaThreeCode' => 'VIR', 'countryCode' => 850),
            array('countryName' => 'Wallis and Futuna', 'alphaTwoCode' => 'WF', 'alphaThreeCode' => 'WLF', 'countryCode' => 876),
            array('countryName' => 'Western Sahara', 'alphaTwoCode' => 'EH', 'alphaThreeCode' => 'ESH', 'countryCode' => 732),
            array('countryName' => 'Yemen', 'alphaTwoCode' => 'YE', 'alphaThreeCode' => 'YEM', 'countryCode' => 887),
            array('countryName' => 'Zambia', 'alphaTwoCode' => 'ZM', 'alphaThreeCode' => 'ZMB', 'countryCode' => 894),
            array('countryName' => 'Zimbabwe', 'alphaTwoCode' => 'ZW', 'alphaThreeCode' => 'ZWE', 'countryCode' => 716),
            array('countryName' => 'Åland Islands', 'alphaTwoCode' => 'AX', 'alphaThreeCode' => 'ALA', 'countryCode' => 248)
        );
        Country::insert($country);
    }
}
